// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBx3Dk6EX0WkLPmQWkBTBA3Ti0qf_kJajA',
    appId: '1:629101879312:web:43f1a4e4a0be1691316a95',
    messagingSenderId: '629101879312',
    projectId: 'firecrud-39ef1',
    authDomain: 'firecrud-39ef1.firebaseapp.com',
    storageBucket: 'firecrud-39ef1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVboZphptV16HFo1FjnZ4hW5LMzcJszW8',
    appId: '1:629101879312:android:904d33c5cf649f90316a95',
    messagingSenderId: '629101879312',
    projectId: 'firecrud-39ef1',
    storageBucket: 'firecrud-39ef1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDD-iRBj5uA3AJRVqGQTuI9KO_86hhiADI',
    appId: '1:629101879312:ios:0d66ef097266f59a316a95',
    messagingSenderId: '629101879312',
    projectId: 'firecrud-39ef1',
    storageBucket: 'firecrud-39ef1.appspot.com',
    iosBundleId: 'com.example.firebasetask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDD-iRBj5uA3AJRVqGQTuI9KO_86hhiADI',
    appId: '1:629101879312:ios:0d66ef097266f59a316a95',
    messagingSenderId: '629101879312',
    projectId: 'firecrud-39ef1',
    storageBucket: 'firecrud-39ef1.appspot.com',
    iosBundleId: 'com.example.firebasetask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBx3Dk6EX0WkLPmQWkBTBA3Ti0qf_kJajA',
    appId: '1:629101879312:web:e9bd8bd011b993c9316a95',
    messagingSenderId: '629101879312',
    projectId: 'firecrud-39ef1',
    authDomain: 'firecrud-39ef1.firebaseapp.com',
    storageBucket: 'firecrud-39ef1.appspot.com',
  );
}
